apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-app
  namespace: ocr
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
  - host: ocr.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ocr-frontend
            port:
              number: 80
